# AppVeyor build configuration
#
# doc: http://www.appveyor.com/docs/build-configuration
# Qt-versions: https://www.appveyor.com/docs/build-environment/#qt
# validator: https://ci.appveyor.com/tools/validate-yaml

os: unstable
skip_tags: true

environment:
  global:
    qtdir57: C:\Qt\5.7\mingw53_32
    qtdir59: C:\Qt\5.10.1\mingw53_32

  matrix:
    # Qt 5.10
    - qtdir: "C:\\Qt\\5.10.1\\mingw53_32"
    # Qt 5.7 (for Windows XP)
    - qtdir: "C:\\Qt\\5.7\\mingw53_32"

matrix:
  allow_failures:
    - qtdir: "C:\\Qt\\5.7\\mingw53_32"

install:
  # Qt-versions: https://www.appveyor.com/docs/build-environment/#qt
#  - set QTDIR=C:\Qt\5.7\mingw53_32
#  - set QTDIR=C:\Qt\5.10.1\mingw53_32
  - set QTDIR=%qtdir%
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  - set RELEASE_PATH=appveyor\release

before_build:
  # getting submodules
  - git submodule update --init

build_script:
  # enable this to take a look if there are new qt versions
#  - dir C:\Qt\
#  - dir C:\Qt\5.8
  - cd src
  # we need to modify that to make it running on AppVeyor
  - sed -i "s/CONFIG += c++11/QMAKE_CXXFLAGS += -std=gnu++0x/g" QOwnNotes.pro
  - "echo #define RELEASE \"AppVeyor\" > release.h"
  # setting the build number in the header file
  - "echo #define BUILD %APPVEYOR_BUILD_NUMBER% > build_number.h"
  - qmake QOwnNotes.pro -r -spec win32-g++
#  - qmake QOwnNotes.pro -r -spec win32-g++ "CONFIG+=debug"
  - mingw32-make
  # creating the release path
  - md ..\%RELEASE_PATH%
  # copy the binary to our release path
  - copy release\QOwnNotes.exe ..\%RELEASE_PATH%
  # copy OpenSSL DLLs to the release path
  - copy ..\appveyor\OpenSSL\libeay32.dll ..\%RELEASE_PATH%
  - copy ..\appveyor\OpenSSL\libssl32.dll ..\%RELEASE_PATH%
  - copy ..\appveyor\OpenSSL\ssleay32.dll ..\%RELEASE_PATH%
  # copy unzip application for updater
  - copy ..\appveyor\unzip.exe ..\%RELEASE_PATH%
  # copy updater script
  - copy ..\appveyor\update.bat ..\%RELEASE_PATH%
  # copy portable mode launcher to the release path
  - copy ..\appveyor\QOwnNotesPortable.bat ..\%RELEASE_PATH%
  # copy translation files
  - copy languages\*.qm ..\%RELEASE_PATH%
  - cd ..\%RELEASE_PATH%
  # fetching dependencies of QT app
  # http://doc.qt.io/qt-5/windows-deployment.html
  - windeployqt --release QOwnNotes.exe
  # this dll was missed by windeployqt
  - copy ..\libwinpthread-1.dll . /y
  # this dll didn't work when released by windeployqt
  # important: this dll needs to be updated when a new version of Qt is used!
  # search for it in the mingw* folder of your local installation of Qt
  - copy "..\libstdc++-6.dll" . /y
  # for some reason AppVeyor or windeployqt uses a copy of the German
  # translation file as English one, which screws up the English user interface
  - del "translations\qt_en.qm"

artifacts:
  # pushing entire folder as a zip archive
  - path: appveyor\release
    name: QOwnNotes

deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: QOwnNotes
    draft: false
    prerelease: false
    auth_token:
      secure: spcyN/Dz3B2GXBPii8IywDLq6vfxC1SrN+xR2wMerFM7g2nTy0Lrh5agQONFoInR
    on:
      branch: master
      qtdir: "C:\\Qt\\5.10.1\\mingw53_32"
#      branch: develop

notifications:
  # Gitter webhook
  - provider: Webhook
    url: https://webhooks.gitter.im/e/b6ef22402eb4af50f73a
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false
